apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:4.1.1
          ports:
            - containerPort: 3000
          env:
            - name: REDMINE_DB_POSTGRES
              value: database
            - name: REDMINE_DB_USERNAME
              value: testuser
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDMINE_DB_DATABASE
              value: testdb
            - name: REDMINE_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: REDMINE_SECRET_KEY_BASE
          volumeMounts:
            - name: redmine-persistent-storage
              mountPath: "/usr/src/redmine/files"
      volumes:
        - name: redmine-persistent-storage
          persistentVolumeClaim:
            claimName: pg-pvc-ssd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0          
